[CC]
CC_100_01p1m = "[C+0:1]-[C+0:2]>>[C+1:1].[C-1:2]"
CC_01p1m_100 = "[C+1:1].[C-1:2]>>[C+0:1]-[C+0:2]"
CC_200_11p1m = "[C+0:1]=[C+0:2]>>[C+1:1]-[C-1:2]"
CC_11p1m_200 = "[C+1:1]-[C-1:2]>>[C+0:1]=[C+0:2]"
CC_300_21p1m = "[C+0:1]#[C+0:2]>>[C+1:1]=[C-1:2]"
CC_21p1m_300 = "[C+1:1]=[C-1:2]>>[C+0:1]#[C+0:2]"

[HC]
HC_100_01p1m = "[H+0:1]-[C+0:2]>>[H+1:1].[C-1:2]"
HC_01p1m_100 = "[H+1:1].[C-1:2]>>[H+0:1]-[C+0:2]"

[CO]
CO_100_01p1m = "[C+0:1]-[O+0:2]>>[C+1:1].[O-1:2]"
CO_01p1m_100 = "[C+1:1].[O-1:2]>>[C+0:1]-[O+0:2]"
CO_101p_01p0 = "[C+0:1]-[O+1:2]>>[C+1:1].[O+0:2]"
CO_01p0_101p = "[C+1:1].[O+0:2]>>[C+0:1]-[O+1:2]"
CO_200_11p1m = "[C+0:1]=[O+0:2]>>[C+1:1]-[O-1:2]"
CO_11p1m_200 = "[C+1:1]-[O-1:2]>>[C+0:1]=[O+0:2]"
CO_201p_11p0 = "[C+0:1]=[O+1:2]>>[C+1:1]-[O+0:2]"
CO_11p0_201p = "[C+1:1]-[O+0:2]>>[C+0:1]=[O+1:2]"
CO_300_21p1m = "[C+0:1]#[O+0:2]>>[C+1:1]=[O-1:2]"
CO_21p1m_300 = "[C+1:1]=[O-1:2]>>[C+0:1]#[O+0:2]"
CO_301p_21p0 = "[C+0:1]#[O+1:2]>>[C+1:1]=[O+0:2]"
CO_201m_301p = "[C+1:1]=[O+0:2]>>[C+0:1]#[O+1:2]"

[OH]
OH_100_01m1p = "[O+0:1]-[H+0:2]>>[O-1:1].[H+1:2]"
OH_01m1p_100 = "[O-1:1].[H+1:2]>>[O+0:1]-[H+0:2]"
OH_11p0_001p = "[O+1:1]-[H+0:2]>>[O+0:1].[H+1:2]"
OH_001p_11p0 = "[O+0:1].[H+1:2]>>[O+1:1]-[H+0:2]"

[CN]
CN_100_01p1m = "[C+0:1]-[N+0:2]>>[C+1:1].[N-1:2]"
CN_01p1m_100 = "[C+1:1].[N-1:2]>>[C+0:1]-[N+0:2]"
CN_101p_01p0 = "[C+0:1]-[N+1:2]>>[C+1:1].[N+0:2]"
CN_01p0_101p = "[C+1:1].[N+0:2]>>[C+0:1]-[N+1:2]"
CN_200_11p1m = "[C+0:1]=[N+0:2]>>[C+1:1]-[N-1:2]"
CN_11p1m_200 = "[C+1:1]-[N-1:2]>>[C+0:1]=[N+0:2]"
CN_201p_11p0 = "[C+0:1]=[N+1:2]>>[C+1:1]-[N+0:2]"
CN_11p0_201p = "[C+1:1]-[N+0:2]>>[C+0:1]=[N+1:2]"
CN_300_21p1m = "[C+0:1]#[N+0:2]>>[C+1:1]=[N-1:2]"
CN_21p1m_300 = "[C+1:1]=[N-1:2]>>[C+0:1]#[N+0:2]"
CN_301p_21p0 = "[C+0:1]#[N+1:2]>>[C+1:1]=[N+0:2]"
CN_21p0_301p = "[C+1:1]=[N+0:2]>>[C+0:1]#[N+1:2]"

[HN]
HN_100_01p1m = "[H+0:1]-[N+0:2]>>[H+1:1].[N-1:2]"
HN_01p1m_100 = "[H+1:1].[N-1:2]>>[H+0:1]-[N+0:2]"
HN_101p_01p0 = "[H+0:1]-[N+1:2]>>[H+1:1].[N+0:2]"
HN_01p0_101p = "[H+1:1].[N+0:2]>>[H+0:1]-[N+1:2]"

[Halogens]
CF_dissociation = "[C+0:1]-[F+0:2]>>[C+1:1].[F-1:2]"
CF_association = "[C+1:1].[F-1:2]>>[C+0:1]-[F+0:2]"
FC_dissociation = "[F+0:1]-[C+0:2]>>[F+1;H0:1].[C-1:2]"
FC_association = "[F+1:1].[C-1:2]>>[F+0:1]-[C+0:2]"
HF_dissociation = "[H+0:1]-[F+0:2]>>[H+1:1].[F-1:2]"
HF_association = "[H+1:1].[F-1:2]>>[H+0:1]-[F+0:2]"
FF_dissociation = "[F+0:1]-[F+0:2]>>[F+1;H0:1].[F-1:2]"
FF_association = "[F+1:1].[F-1:2]>>[F+0:1]-[F+0:2]"
CCl_dissociation = "[C+0:1]-[Cl+0:2]>>[C+1:1].[Cl-1:2]"
CCl_association = "[C+1:1].[Cl-1:2]>>[C+0:1]-[Cl+0:2]"
ClC_dissociation = "[Cl+0:1]-[C+0:2]>>[Cl+1;H0:1].[C-1:2]"
ClC_association = "[Cl+1:1].[C-1:2]>>[Cl+0:1]-[C+0:2]"
HCl_dissociation = "[H+0:1]-[Cl+0:2]>>[H+1:1].[Cl-1:2]"
HCl_association = "[H+1:1].[Cl-1:2]>>[H+0:1]-[Cl+0:2]"
ClCl_dissociation = "[Cl+0:1]-[Cl+0:2]>>[Cl+1;H0:1].[Cl-1:2]"
ClCl_association = "[Cl+1:1].[Cl-1:2]>>[Cl+0:1]-[Cl+0:2]"
CBr_dissociation = "[C+0:1]-[Br+0:2]>>[C+1:1].[Br-1:2]"
CBr_association = "[C+1:1].[Br-1:2]>>[C+0:1]-[Br+0:2]"
BrC_dissociation = "[Br+0:1]-[C+0:2]>>[Br+1;H0:1].[C-1:2]"
BrC_association = "[Br+1:1].[C-1:2]>>[Br+0:1]-[C+0:2]"
HBr_dissociation = "[H+0:1]-[Br+0:2]>>[H+1:1].[Br-1:2]"
HBr_association = "[H+1:1].[Br-1:2]>>[H+0:1]-[Br+0:2]"
BrBr_dissociation = "[Br+0:1]-[Br+0:2]>>[Br+1;H0:1].[Br-1:2]"
BrBr_association = "[Br+1:1].[Br-1:2]>>[Br+0:1]-[Br+0:2]"
CI_dissociation = "[C+0:1]-[I+0:2]>>[C+1:1].[I-1:2]"
CI_association = "[C+1:1].[I-1:2]>>[C+0:1]-[I+0:2]"
IC_dissociation = "[I+0:1]-[C+0:2]>>[I+1;H0:1].[C-1:2]"
IC_association = "[I+1:1].[C-1:2]>>[I+0:1]-[C+0:2]"
HI_dissociation = "[H+0:1]-[I+0:2]>>[H+1:1].[I-1:2]"
HI_association = "[H+1:1].[I-1:2]>>[H+0:1]-[I+0:2]"
II_dissociation = "[I+0:1]-[I+0:2]>>[I+1;H0:1].[I-1:2]"
II_association = "[I+1:1].[I-1:2]>>[I+0:1]-[I+0:2]"
FCl_dissociation = "[F+0:1]-[Cl+0:2]>>[F+1;H0:1].[Cl-1:2]"
FCl_association = "[F+1:1].[Cl-1:2]>>[F+0:1]-[Cl+0:2]"
FBr_dissociation = "[F+0:1]-[Br+0:2]>>[F+1;H0:1].[Br-1:2]"
FBr_association = "[F+1:1].[Br-1:2]>>[F+0:1]-[Br+0:2]"
FI_dissociation = "[F+0:1]-[I+0:2]>>[F+1;H0:1].[I-1:2]"
FI_association = "[F+1:1].[I-1:2]>>[F+0:1]-[I+0:2]"
ClF_dissociation = "[Cl+0:1]-[F+0:2]>>[Cl+1;H0:1].[F-1:2]"
ClF_association = "[Cl+1:1].[F-1:2]>>[Cl+0:1]-[F+0:2]"
ClBr_dissociation = "[Cl+0:1]-[Br+0:2]>>[Cl+1;H0:1].[Br-1:2]"
ClBr_association = "[Cl+1:1].[Br-1:2]>>[Cl+0:1]-[Br+0:2]"
ClI_dissociation = "[Cl+0:1]-[I+0:2]>>[Cl+1;H0:1].[I-1:2]"
ClI_association = "[Cl+1:1].[I-1:2]>>[Cl+0:1]-[I+0:2]"
BrF_dissociation = "[Br+0:1]-[F+0:2]>>[Br+1;H0:1].[F-1:2]"
BrF_association = "[Br+1:1].[F-1:2]>>[Br+0:1]-[F+0:2]"
BrCl_dissociation = "[Br+0:1]-[Cl+0:2]>>[Br+1;H0:1].[Cl-1:2]"
BrCl_association = "[Br+1:1].[Cl-1:2]>>[Br+0:1]-[Cl+0:2]"
BrI_dissociation = "[Br+0:1]-[I+0:2]>>[Br+1;H0:1].[I-1:2]"
BrI_association = "[Br+1:1].[I-1:2]>>[Br+0:1]-[I+0:2]"
IF_dissociation = "[I+0:1]-[F+0:2]>>[I+1;H0:1].[F-1:2]"
IF_association = "[I+1:1].[F-1:2]>>[I+0:1]-[F+0:2]"
ICl_dissociation = "[I+0:1]-[Cl+0:2]>>[I+1;H0:1].[Cl-1:2]"
ICl_association = "[I+1:1].[Cl-1:2]>>[I+0:1]-[Cl+0:2]"
IBr_dissociation = "[I+0:1]-[Br+0:2]>>[I+1;H0:1].[Br-1:2]"
IBr_association = "[I+1:1].[Br-1:2]>>[I+0:1]-[Br+0:2]"

[C_halogen]
CF_101p_01p0 = "[C+0:1]-[F+1:2]>>[C+1:1].[F+0:2]"
CF_01p0_101p = "[C+1:1].[F+0:2]>>[C+0:1]-[F+1;H0:2]"
CI_101p_01p0 = "[C+0:1]-[I+1:2]>>[C+1:1].[I+0:2]"
CI_01p0_101p = "[C+1:1].[I+0:2]>>[C+0:1]-[I+1;H0:2]"
CCl_101p_01p0 = "[C+0:1]-[Cl+1:2]>>[C+1:1].[Cl+0:2]"
CCl_01p0_101p = "[C+1:1].[Cl+0:2]>>[C+0:1]-[Cl+1;H0:2]"
CBr_101p_01p0 = "[C+0:1]-[Br+1:2]>>[C+1:1].[Br+0:2]"
CBr_01p0_101p = "[C+1:1].[Br+0:2]>>[C+0:1]-[Br+1;H0:2]"

[Rings_CC]
R3_CC  = "[C+0:1]1[*:2][C+0:3]1>>[C+1:1][*:2][C-1:3]"
R4_CC  = "[C+0:1]1[*:2][*:3][C+0:4]1>>[C+1:1][*:2][*:3][C-1:4]"
R5_CC  = "[C+0:1]1[*:2][*:3][*:4][C+0:5]1>>[C+1:1][*:2][*:3][*:4][C-1:5]"
R6_CC  = "[C+0:1]1[*:2][*:3][*:4][*:5][C+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][C-1:6]"

[Rings_CO]
R3_CO  = "[C+0:1]1[*:2][O+0:3]1>>[C+1:1][*:2][O-1:3]"
R4_CO  = "[C+0:1]1[*:2][*:3][O+0:4]1>>[C+1:1][*:2][*:3][O-1:4]"
R5_CO  = "[C+0:1]1[*:2][*:3][*:4][O+0:5]1>>[C+1:1][*:2][*:3][*:4][O-1:5]"
R6_CO  = "[C+0:1]1[*:2][*:3][*:4][*:5][O+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][O-1:6]"

R3_COp = "[C+0:1]1[*:2][O+1:3]1>>[C+1:1][*:2][O+0:3]"
R4_COp = "[C+0:1]1[*:2][*:3][O+1:4]1>>[C+1:1][*:2][*:3][O+0:4]"
R5_COp = "[C+0:1]1[*:2][*:3][*:4][O+1:5]1>>[C+1:1][*:2][*:3][*:4][O+0:5]"
R6_COp = "[C+0:1]1[*:2][*:3][*:4][*:5][O+1:6]1>>[C+1:1][*:2][*:3][*:4][*:5][O+0:6]"

[Rings_CN]
R3_CN  = "[C+0:1]1[*:2][N+0:3]1>>[C+1:1][*:2][N-1:3]"
R4_CN  = "[C+0:1]1[*:2][*:3][N+0:4]1>>[C+1:1][*:2][*:3][N-1:4]"
R5_CN  = "[C+0:1]1[*:2][*:3][*:4][N+0:5]1>>[C+1:1][*:2][*:3][*:4][N-1:5]"
R6_CN  = "[C+0:1]1[*:2][*:3][*:4][*:5][N+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][N-1:6]"

R3_CNp = "[C+0:1]1[*:2][N+1:3]1>>[C+1:1][*:2][N+0:3]"
R4_CNp = "[C+0:1]1[*:2][*:3][N+1:4]1>>[C+1:1][*:2][*:3][N+0:4]"
R5_CNp = "[C+0:1]1[*:2][*:3][*:4][N+1:5]1>>[C+1:1][*:2][*:3][*:4][N+0:5]"
R6_CNp = "[C+0:1]1[*:2][*:3][*:4][*:5][N+1:6]1>>[C+1:1][*:2][*:3][*:4][*:5][N+0:6]"

[Rings_CBr]
R3_CBr = "[C+0:1]1[*:2][Br+0:3]1>>[C+1:1][*:2][Br-1:3]"
R4_CBr = "[C+0:1]1[*:2][*:3][Br+0:4]1>>[C+1:1][*:2][*:3][Br-1:4]"
R5_CBr = "[C+0:1]1[*:2][*:3][*:4][Br+0:5]1>>[C+1:1][*:2][*:3][*:4][Br-1:5]"
R6_CBr = "[C+0:1]1[*:2][*:3][*:4][*:5][Br+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][Br-1:6]"

[Rings_CF]
R3_CF  = "[C+0:1]1[*:2][F+0:3]1>>[C+1:1][*:2][F-1:3]"
R4_CF  = "[C+0:1]1[*:2][*:3][F+0:4]1>>[C+1:1][*:2][*:3][F-1:4]"
R5_CF  = "[C+0:1]1[*:2][*:3][*:4][F+0:5]1>>[C+1:1][*:2][*:3][*:4][F-1:5]"
R6_CF  = "[C+0:1]1[*:2][*:3][*:4][*:5][F+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][F-1:6]"

[Rings_CI]
R3_CI  = "[C+0:1]1[*:2][I+0:3]1>>[C+1:1][*:2][I-1:3]"
R4_CI  = "[C+0:1]1[*:2][*:3][I+0:4]1>>[C+1:1][*:2][*:3][I-1:4]"
R5_CI  = "[C+0:1]1[*:2][*:3][*:4][I+0:5]1>>[C+1:1][*:2][*:3][*:4][I-1:5]"
R6_CI  = "[C+0:1]1[*:2][*:3][*:4][*:5][I+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][I-1:6]"

[Rings_CCl]
R3_CCl = "[C+0:1]1[*:2][Cl+0:3]1>>[C+1:1][*:2][Cl-1:3]"
R4_CCl = "[C+0:1]1[*:2][*:3][Cl+0:4]1>>[C+1:1][*:2][*:3][Cl-1:4]"
R5_CCl = "[C+0:1]1[*:2][*:3][*:4][Cl+0:5]1>>[C+1:1][*:2][*:3][*:4][Cl-1:5]"
R6_CCl = "[C+0:1]1[*:2][*:3][*:4][*:5][Cl+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][Cl-1:6]"