[CC]
CC_100_01p1m = "[C+0:1]-[C+0:2]>>[C+1:1].[C-1:2]"
CC_01p1m_100 = "[C+1:1].[C-1:2]>>[C+0:1]-[C+0:2]"
CC_200_11p1m = "[C+0:1]=[C+0:2]>>[C+1:1]-[C-1:2]"
CC_11p1m_200 = "[C+1:1]-[C-1:2]>>[C+0:1]=[C+0:2]"
CC_300_21p1m = "[C+0:1]#[C+0:2]>>[C+1:1]=[C-1:2]"
CC_21p1m_300 = "[C+1:1]=[C-1:2]>>[C+0:1]#[C+0:2]"

[HC]
HC_100_01p1m = "[H+0:1]-[C+0:2]>>[H+1:1].[C-1:2]"
HC_01p1m_100 = "[H+1:1].[C-1:2]>>[H+0:1]-[C+0:2]"

[CO]
CO_100_01p1m = "[C+0:1]-[O+0:2]>>[C+1:1].[O-1:2]"
CO_01p1m_100 = "[C+1:1].[O-1:2]>>[C+0:1]-[O+0:2]"
CO_101p_01p0 = "[C+0:1]-[O+1:2]>>[C+1:1].[O+0:2]"
CO_01p0_101p = "[C+1:1].[O+0:2]>>[C+0:1]-[O+1:2]"
CO_200_11p1m = "[C+0:1]=[O+0:2]>>[C+1:1]-[O-1:2]"
CO_11p1m_200 = "[C+1:1]-[O-1:2]>>[C+0:1]=[O+0:2]"
CO_201p_11p0 = "[C+0:1]=[O+1:2]>>[C+1:1]-[O+0:2]"
CO_11p0_201p = "[C+1:1]-[O+0:2]>>[C+0:1]=[O+1:2]"
CO_300_21p1m = "[C+0:1]#[O+0:2]>>[C+1:1]=[O-1:2]"
CO_21p1m_300 = "[C+1:1]=[O-1:2]>>[C+0:1]#[O+0:2]"
CO_301p_21p0 = "[C+0:1]#[O+1:2]>>[C+1:1]=[O+0:2]"
CO_201m_301p = "[C+1:1]=[O+0:2]>>[C+0:1]#[O+1:2]"

[OH]
OH_100_01m1p = "[O+0:1]-[H+0:2]>>[O-1:1].[H+1:2]"
OH_01m1p_100 = "[O-1:1].[H+1:2]>>[O+0:1]-[H+0:2]"
OH_11p0_001p = "[O+1:1]-[H+0:2]>>[O+0:1].[H+1:2]"
OH_001p_11p0 = "[O+0:1].[H+1:2]>>[O+1:1]-[H+0:2]"

[CN]
CN_100_01p1m = "[C+0:1]-[N+0:2]>>[C+1:1].[N-1:2]"
CN_01p1m_100 = "[C+1:1].[N-1:2]>>[C+0:1]-[N+0:2]"
CN_101p_01p0 = "[C+0:1]-[N+1:2]>>[C+1:1].[N+0:2]"
CN_01p0_101p = "[C+1:1].[N+0:2]>>[C+0:1]-[N+1:2]"
CN_200_11p1m = "[C+0:1]=[N+0:2]>>[C+1:1]-[N-1:2]"
CN_11p1m_200 = "[C+1:1]-[N-1:2]>>[C+0:1]=[N+0:2]"
CN_201p_11p0 = "[C+0:1]=[N+1:2]>>[C+1:1]-[N+0:2]"
CN_11p0_201p = "[C+1:1]-[N+0:2]>>[C+0:1]=[N+1:2]"
CN_300_21p1m = "[C+0:1]#[N+0:2]>>[C+1:1]=[N-1:2]"
CN_21p1m_300 = "[C+1:1]=[N-1:2]>>[C+0:1]#[N+0:2]"
CN_301p_21p0 = "[C+0:1]#[N+1:2]>>[C+1:1]=[N+0:2]"
CN_21p0_301p = "[C+1:1]=[N+0:2]>>[C+0:1]#[N+1:2]"

[HN]
HN_100_01p1m = "[H+0:1]-[N+0:2]>>[H+1:1].[N-1:2]"
HN_01p1m_100 = "[H+1:1].[N-1:2]>>[H+0:1]-[N+0:2]"
HN_101p_01p0 = "[H+0:1]-[N+1:2]>>[H+1:1].[N+0:2]"
HN_01p0_101p = "[H+1:1].[N+0:2]>>[H+0:1]-[N+1:2]"

[Halogens]
CF_dissociation = "[C+0:1]-[F+0:2]>>[C+1:1].[F-1:2]"
CF_association = "[C+1:1].[F-1:2]>>[C+0:1]-[F+0:2]"
FC_dissociation = "[F+0:1]-[C+0:2]>>[F+1;H0:1].[C-1:2]"
FC_association = "[F+1:1].[C-1:2]>>[F+0:1]-[C+0:2]"
HF_dissociation = "[H+0:1]-[F+0:2]>>[H+1:1].[F-1:2]"
HF_association = "[H+1:1].[F-1:2]>>[H+0:1]-[F+0:2]"
FF_dissociation = "[F+0:1]-[F+0:2]>>[F+1;H0:1].[F-1:2]"
FF_association = "[F+1:1].[F-1:2]>>[F+0:1]-[F+0:2]"
CCl_dissociation = "[C+0:1]-[Cl+0:2]>>[C+1:1].[Cl-1:2]"
CCl_association = "[C+1:1].[Cl-1:2]>>[C+0:1]-[Cl+0:2]"
ClC_dissociation = "[Cl+0:1]-[C+0:2]>>[Cl+1;H0:1].[C-1:2]"
ClC_association = "[Cl+1:1].[C-1:2]>>[Cl+0:1]-[C+0:2]"
HCl_dissociation = "[H+0:1]-[Cl+0:2]>>[H+1:1].[Cl-1:2]"
HCl_association = "[H+1:1].[Cl-1:2]>>[H+0:1]-[Cl+0:2]"
ClCl_dissociation = "[Cl+0:1]-[Cl+0:2]>>[Cl+1;H0:1].[Cl-1:2]"
ClCl_association = "[Cl+1:1].[Cl-1:2]>>[Cl+0:1]-[Cl+0:2]"
CBr_dissociation = "[C+0:1]-[Br+0:2]>>[C+1:1].[Br-1:2]"
CBr_association = "[C+1:1].[Br-1:2]>>[C+0:1]-[Br+0:2]"
BrC_dissociation = "[Br+0:1]-[C+0:2]>>[Br+1;H0:1].[C-1:2]"
BrC_association = "[Br+1:1].[C-1:2]>>[Br+0:1]-[C+0:2]"
HBr_dissociation = "[H+0:1]-[Br+0:2]>>[H+1:1].[Br-1:2]"
HBr_association = "[H+1:1].[Br-1:2]>>[H+0:1]-[Br+0:2]"
BrBr_dissociation = "[Br+0:1]-[Br+0:2]>>[Br+1;H0:1].[Br-1:2]"
BrBr_association = "[Br+1:1].[Br-1:2]>>[Br+0:1]-[Br+0:2]"
CI_dissociation = "[C+0:1]-[I+0:2]>>[C+1:1].[I-1:2]"
CI_association = "[C+1:1].[I-1:2]>>[C+0:1]-[I+0:2]"
IC_dissociation = "[I+0:1]-[C+0:2]>>[I+1;H0:1].[C-1:2]"
IC_association = "[I+1:1].[C-1:2]>>[I+0:1]-[C+0:2]"
HI_dissociation = "[H+0:1]-[I+0:2]>>[H+1:1].[I-1:2]"
HI_association = "[H+1:1].[I-1:2]>>[H+0:1]-[I+0:2]"
II_dissociation = "[I+0:1]-[I+0:2]>>[I+1;H0:1].[I-1:2]"
II_association = "[I+1:1].[I-1:2]>>[I+0:1]-[I+0:2]"
FCl_dissociation = "[F+0:1]-[Cl+0:2]>>[F+1;H0:1].[Cl-1:2]"
FCl_association = "[F+1:1].[Cl-1:2]>>[F+0:1]-[Cl+0:2]"
FBr_dissociation = "[F+0:1]-[Br+0:2]>>[F+1;H0:1].[Br-1:2]"
FBr_association = "[F+1:1].[Br-1:2]>>[F+0:1]-[Br+0:2]"
FI_dissociation = "[F+0:1]-[I+0:2]>>[F+1;H0:1].[I-1:2]"
FI_association = "[F+1:1].[I-1:2]>>[F+0:1]-[I+0:2]"
ClF_dissociation = "[Cl+0:1]-[F+0:2]>>[Cl+1;H0:1].[F-1:2]"
ClF_association = "[Cl+1:1].[F-1:2]>>[Cl+0:1]-[F+0:2]"
ClBr_dissociation = "[Cl+0:1]-[Br+0:2]>>[Cl+1;H0:1].[Br-1:2]"
ClBr_association = "[Cl+1:1].[Br-1:2]>>[Cl+0:1]-[Br+0:2]"
ClI_dissociation = "[Cl+0:1]-[I+0:2]>>[Cl+1;H0:1].[I-1:2]"
ClI_association = "[Cl+1:1].[I-1:2]>>[Cl+0:1]-[I+0:2]"
BrF_dissociation = "[Br+0:1]-[F+0:2]>>[Br+1;H0:1].[F-1:2]"
BrF_association = "[Br+1:1].[F-1:2]>>[Br+0:1]-[F+0:2]"
BrCl_dissociation = "[Br+0:1]-[Cl+0:2]>>[Br+1;H0:1].[Cl-1:2]"
BrCl_association = "[Br+1:1].[Cl-1:2]>>[Br+0:1]-[Cl+0:2]"
BrI_dissociation = "[Br+0:1]-[I+0:2]>>[Br+1;H0:1].[I-1:2]"
BrI_association = "[Br+1:1].[I-1:2]>>[Br+0:1]-[I+0:2]"
IF_dissociation = "[I+0:1]-[F+0:2]>>[I+1;H0:1].[F-1:2]"
IF_association = "[I+1:1].[F-1:2]>>[I+0:1]-[F+0:2]"
ICl_dissociation = "[I+0:1]-[Cl+0:2]>>[I+1;H0:1].[Cl-1:2]"
ICl_association = "[I+1:1].[Cl-1:2]>>[I+0:1]-[Cl+0:2]"
IBr_dissociation = "[I+0:1]-[Br+0:2]>>[I+1;H0:1].[Br-1:2]"
IBr_association = "[I+1:1].[Br-1:2]>>[I+0:1]-[Br+0:2]"